$(document).ready(function(){
$('img.facebook').hover(function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/facebook-icon-hover.png');
},function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/facebook-icon.png');
});
$('img.twitter').hover(function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/twitter-icon-hover.png');
},function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/twitter-icon.png');
});
$('img.linkedin').hover(function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/linkedin-icon-hover.png');
},function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/linkedin-icon.png');
});
$('img.youtube').hover(function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/youtube-icon-hover.png');
},function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/youtube-icon.png');
});
$('input.icon').hover(function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/search-hover.png');
},function(){
$(this).attr('src','http://davidtproductions.com/wp-content/themes/davidtproductions-theme/images/search.png');
});
});